spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=pirate
spring.application.name=backendProgrammering
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.web.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false